apiVersion: ndb.nutanix.com/v1alpha1
kind: Database
metadata:
  name: db
spec:
  ndb:
    remoteType: "cloud"
    clusterId: "a3583bb6-6abc-492b-82de-010564617e7d"
    credentialSecret : ntnx4-ndb-secret
    server: https://ndb.nutanix.com/era/v1.0
    skipCertificateVerification: true
  databaseInstance:
    databaseInstanceName: "Database Instance Name"
    databaseNames:
      - database_one
      - database_two
      - database_three
    credentialSecret: db-instance-secret-name
    size: 10
    timezone: "UTC"
    type: postgres