apiVersion: v1
kind: Secret
metadata:
  name: your-ndb-secret
type: Opaque
stringData:
  username: username-for-ndb-server
  password: password-for-ndb-server
---
apiVersion: v1
kind: Secret
metadata:
  name: your-db-secret
type: Opaque
stringData:
  password: password-for-the-database-instance
  ssh_public_key: SSH-PUBLIC-KEY