apiVersion: v1
kind: Secret
metadata:
  name: ntnx4-ndb-secret
type: Opaque
stringData:
  username: NTNX-4
  password: NTNX-4
---
apiVersion: v1
kind: Secret
metadata:
  name: ntnx4-ndb-secret
type: Opaque
stringData:
  password: password
  ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCnviAEPjibAwK15HN9t599xlIxI0h7z2LzDT69jQkq3PAbO2KS6aEQtplALm0Ih8aHGzSop5aVa6KlM4c7OLqKlPjMBeU8ZALUmffEv4Sn01MoguLH/Idm1fJ1sVKR+8QCNt8Np5AYQ3xAOPTb7srjbVKebE8QFx+OCUE7E0MvXUgpZENlykKDLmtzDMFjxtaW4KmdcDcib4IlXuhgv3DEDihGAOd0QusexOumeFonn5oERIzZeWAzU//EQRRACSOPb5TgtVSH/ZKPQU23EINCOTMfmiBWN/nZ027K+AV62KDPl5/zctk8SBXvb88IqBA7SlN9x2lCXY0iplCtc15Dgmq6QNKT50kIYzzzp+IKLHWXx50zLZntud0W2704m3o+h8Vtf0AuRgWgzPeV+bgpYruX9tmizs87Q9RkMO4dwlXKJxkyMk+/1nvw4MkPTucR8t+luup1yfj/1dZS30KsCa1XuIXNT6h38FSCV8ciGuyZGH8NCJ/Xzs5REQXp8Jk=